# Generated by Django 5.0.4 on 2024-04-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventry',
            new_name='inventory',
        ),
    ]
