# Generated by Django 5.0.4 on 2024-04-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_inventry_product_inventory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
